### ISSUE TITLE
Support RDS (and other) metrics

### ISSUE THREAD

**Issue by arabold** [EagerELK/logstash-input-cloudwatch#1]
The EC2 instance metrics are working great! To me, the second most important metric are the MySQL database servers. So I'm looking forward of having a way of pulling that in as well. Obviously there are plenty of other services that provide data as well. 

Maybe we can build a more generic way of importing stats from different sources? For example, to import both the default EC2 metrics (CPU, Network) and the metrics created by the [CloudWatch monitoring script from Amazon](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/mon-scripts-perl.html) (Memory, Disk), you have to instantiate the CloudWatch plugin configuration twice in Logstash - once the "AWS/EC2" namespace, and once for the "System/Linux" namespace. I was wondering if this couldn't be combined into a single configuration. E.g. by defining the metrics as hash instead of array:
`metrics => { "AWS/EC2" => "CPUUtilization", "System/Linux" => "MemoryUtilization" }`

**Comment by jrgns** [comment]
Hey @arabold , great idea. I'll get into this soonest.

**Comment by jrgns** [comment]
I've created PR #2 to address this. Let's continue the discussion there.
