### ISSUE TITLE
Support for CloudWatch Logs

### ISSUE THREAD

**Issue by jrgns** [EagerELK/logstash-input-cloudwatch#13]
See https://github.com/lukewaite/logstash-input-cloudwatch-logs as an example

**Comment by veewee** [comment]
+1: This one would be very handy!

**Comment by 0x4D31** [comment]
Currently I use Lukewaite's plugin. Is it really needed to support it again in another plugin?
The only problem I have with it is I can't use it for pulling CloudWatch Logs from multiple AWS accounts without using Access Keys. I need to do it using STS. It supports STS but it can't refresh the temporary credentials granted via STS. Here's how it's handled in another plugin:
https://github.com/samcday/logstash-output-kinesis/blob/master/lib/logstash/outputs/kinesis.rb#L154

**Comment by jrgns** [comment]
Since it's supported in another plugin, this is very low priority.

I haven't done a proper review yet, but if this fits into the design of this plugin, I'll include support logs for completeness sake.

Thanx, I'll keep the STS support in mind when looking at it.

**Comment by jrgns** [comment]
Closing this in favour of the issue on logstash-plugins/logstash-input-cloudwatch

**Comment by kasarlajayapal** [comment]
Hello 
Currently i am getting an error .
Does any one has any idea?


[2016-12-02T10:45:16,479][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-02T10:45:16,883][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
**[2016-12-02T10:46:19,473][INFO ][logstash.inputs.cloudwatch] [AWS CloudWatch 200 62.282 3 retries] list_metrics(:namespace=>"AWS/EC2") Timeout::Error execution expired**

[2016-12-02T10:46:19,492][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::CloudWatch namespace=>"AWS/EC2", filters=>{"tag:Name"=>"Logstash", "instance-id"=>"i-*******"}, region=>"us-east-1", period=>900, access_key_id=>"********", secret_access_key=>"******************", session_token=>"***********", id=>"4b8f5f4c9e8bbcbe8424a21513106bbf361bbf7c-1", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_5d6527b4-bb8d-4e3e-9b37-04d299a7d4db", enable_metric=>true, charset=>"UTF-8">, use_ssl=>true, metrics=>["CPUUtilization", "DiskReadOps", "DiskWriteOps", "NetworkIn", "NetworkOut"], statistics=>["SampleCount", "Average", "Minimum", "Maximum", "Sum"], interval=>900, combined=>false>
  **Error: execution expired**
