### ISSUE TITLE
Document configuring AWS access keys

### ISSUE THREAD

**Issue by tdi** [EagerELK/logstash-input-cloudwatch#20]
Now it is very hard to find any information where should API keys be stored.

**Comment by jrgns** [comment]
Configuring Logstash plugins to access AWS services is handled by the Logstash [AWS mixin](https://github.com/logstash-plugins/logstash-mixin-aws). Check out [this blogpost](http://blog.eagerelk.com/accessing-aws-services-with-logstash-plugins/) on how to configure it. It's written for Logstash 1.4, but the Logstash 2 mixin is backwards compatible.

**Comment by tdi** [comment]
Thanks
