### ISSUE TITLE
Compatibility with elasticsearch output plugins

### ISSUE THREAD

**Issue by rhockenbury** [EagerELK/logstash-input-cloudwatch#21]
There's an open issue on logstash for the use of this plugin with elasticsearch output plugins.

https://github.com/elastic/logstash/issues/4375

**Comment by jrgns** [comment]
I've been able to use the plugin along with the Elasticsearch output using the code from logstash-plugins/logstash-input-cloudwatch#3

Can you try that version, or wait until that's merged and try that release?

**Comment by rhockenbury** [comment]
Awesome! Thanks for doing that.  I'll give it a try.

**Comment by jrgns** [comment]
The referenced full request has now been merged. Version 1.1.2 should work fine now.

Can you confirm?
