### ISSUE TITLE
Logstash interval for tagged instances

### ISSUE THREAD

**Issue by goldworth** [EagerELK/logstash-input-cloudwatch#24]
Hello,

I see interval defaults to 900 seconds. I updated my interval input plugin to refresh every 300 seconds interval. It was working when my tag name had one instance. After I added second instance, interval is not working at 300 seconds but at 900 seconds.

input {
  cloudwatch {
    namespace => "AWS/EC2"
    metrics => [ "CPUUtilization", "DiskReadBytes", "DiskReadOps", "DiskWriteBytes", "DiskWriteOps", "NetworkIn", "NetworkOut", "NetworkPacketsIn", "NetworkPacketsOut", "StatusCheckFailed", "StatusCheckFailed_Instance", "StatusCheckFailed_System" ]
    filters => { "tag:name" => "logstash" }
    region => "us-west-2"
    interval => 300
  }
}
output {
    elasticsearch {
        hosts => "escluster:80"
    }
}

Please advise.

**Comment by jrgns** [comment]
Please note that this repository has moved to https://github.com/logstash-plugins/logstash-input-cloudwatch
