### ISSUE TITLE
No data received

### ISSUE THREAD

**Issue by ghost** [EagerELK/logstash-input-cloudwatch#3]
Hey,

I got problems setting up the input. I tried multiple config variations but I don't receive any data. My latest config looks like this.

Input:

```
input {
  cloudwatch {
    tag_name => 'monitored'
    tag_values => [ 'true' ]
    interval => 5
    period => 60
    region => 'ap-southeast-1'
    access_key_id => "xxx"
    secret_access_key => "xxxxxx"
  }
}
```

When running `/opt/logstash/bin/logstash -f /tmp/testconfig --debug`

I can see, that it pulls the correct instances, but the logstash output instances don't receive anything to process

```
[AWS CloudWatch 200 0.053 0 retries] get_metric_statistics(:dimensions=>[{:name=>"InstanceId",:value=>"i-xXxXxXx"}],:end_time=>"2015-08-25T13:35:55+00:00",:metric_name=>"CPUUtilization",:namespace=>"AWS/EC2",:period=>60,:start_time=>"2015-08-25T13:35:50+00:00",:statistics=>["SampleCount","Average","Minimum","Maximum","Sum"])
 {:level=>:info, :file=>"aws/core/client.rb", :line=>"410", :method=>"log_response"}
```

Thanks in advance

**Comment by ghost** [comment]
Seems like a 3rd party problem. `@cloudwatch.get_metric_statistics(opts).data` doesn't contain any datapoints..

**Comment by ghost** [comment]
Solution: `interval => 5` is too little. For me it does work with `interval => 300`. I also tried  `interval => 60`, what did not work. 
I'm not sure why it's not working with a small value.. Maybe latency, undocumented behaviour, internals... No idea

But yeah, great plugin! Thanks man :)

**Comment by jrgns** [comment]
@PhilippWoe Glad you got it working :)

I think you have to enable detailed monitoring for intervals smaller than 15 minutes? I might be thinking of another interval, though.

**Comment by jrgns** [comment]
At second glance, I think if the interval is too small, the plugin starts fetching new metrics before the previous run completes.
