### ISSUE TITLE
Support for EC2 MemoryUtilization Metrics

### ISSUE THREAD

**Issue by jonathanjlin29** [EagerELK/logstash-input-cloudwatch#30]
Here is an AWS document about custom metrics that I have implemented on several of our EC2 instances: [https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html]

I would like to get support for these custom metrics. Specifically, MemoryUtilization and DiskSpaceUtilization.

**Comment by jrgns** [comment]
@jonathanjlin29 Please note that this repository has moved to https://github.com/logstash-plugins/logstash-input-cloudwatch
