### ISSUE TITLE
Feature Request: Log instance tags

### ISSUE THREAD

**Issue by arabold** [EagerELK/logstash-input-cloudwatch#5]
As we're already filtering/searching instances by tags, it should be rather easy to add all user-created tags to the logs. This will allow much simpler filtering in Kibana.

**Comment by jrgns** [comment]
Great idea. Will make work of it.

**Comment by JamesBromberger** [comment]
+1. Cool - would be great if tags included in the message are able to be chosen as a set list (inclusive list), or all tags found, or all tags except a set list (exclusive list).

**Comment by jrgns** [comment]
I've added the basic functionaliy in v0.2.1 - All the instance tags will now be added to the event.

@JamesBromberger It will take some more work to get your request in. Keeping this issue open for that.

**Comment by jrgns** [comment]
I'm marking this as won't fix now now. What you're requesting is meta information around instances, not metric information from CloudWatch. You should be able to use something like a ruby filter to fetch, store and apply the info you want to the events.
