### ISSUE TITLE
Custom dimensions not supported

### ISSUE THREAD

**Issue by Vlad777** [EagerELK/logstash-input-cloudwatch#7]
When requesting metrics, ALL dimensions must be specified in the request. However, it only supports Instance-id as a dimension, so I can't get any results since I'm using custom dimensions.

**Comment by JamesBromberger** [comment]
+1.

You can get back customer metrics if they have an instance_id, for example, using the customer cloudwatchscripts from AWS for populating memory, disk from within the instance - just set the name space and you can pull back by instance id (as that happens to be the dimension).

However, it would be great if one could specify an arbitrary set of filters/dimensions and bring back any metric.

**Comment by jrgns** [comment]
This is now supported in version 1.0.0.

**Comment by jrgns** [comment]
An example config:

``` ruby
input {
  cloudwatch {
    namespace => "My/Worker"
    metrics => [ "TaskDuration" ]
    filters => { "WorkerName" => "CheckFiles" "InstanceId" => "i-4741234" }
    region => "us-east-1"
    combined => true
  }
}
```

The filter need to match the dimensions you used when creating the metric.
